### ISSUE TITLE
Jun 29 To-do list

### ISSUE THREAD

**Issue by RuBBiT-hj** [RuBBiT-hj/causalBETA#4]
- [x] Change bayeshaz documentation
- [x] Dependency of mets
- [x] Documentation for predict function
- [x] Namespace, description?
- [x] Plotting of bayeshaz
- [x] casual inference part

**Comment by RuBBiT-hj** [comment]
#### Question

- [ ] the number of intervals is actually the number of partitions? like the actual interval = partition - 1
- [ ] sometimes the Stan file doesn't update in a R project environment. Does it affect the package?

**Comment by RuBBiT-hj** [comment]
#### Notes

- when install from GitHub, R will try to install packages from cran (and skip cmdstanr because it is not there)

**Comment by RuBBiT-hj** [comment]
### Notes

- Can take use of xv - it is the middle points (seem to be)
